name: Build Android App
## Written by: @ngdplnk for basiccalc

on:
  push:
    branches:
      - main
    paths:
      - 'android-app/*.py'
      - 'android-app/*.kv'
      - 'android-app/*.spec'
      - 'android-app/assets/*.png'
      - '.github/workflows/build-android.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Set up JDK 17
      uses: actions/setup-java@main
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install dependencies
      run: |
        sudo apt update
        pip install cython
        pip install kivy
        pip install kivymd
        pip install buildozer

    - name: Run buildozer
      run: |
        cd android-app/
        buildozer android debug

    - name: Prepare artifacts
      id: prepareArtifact
      run: |
        artifactUpload=`ls -t android-app/bin/*.apk | head -n1`
        artifactName="basiccalc-build${{ github.sha }}-arm64-v8a_armeabi-v7a-debug"
        mv $artifactUpload android-app/bin/$artifactName.apk
        artifactUpload="android-app/bin/$artifactName.apk"
        echo "artifactUpload=$artifactUpload" >> $GITHUB_OUTPUT
        echo "artifactName=$artifactName" >> $GITHUB_OUTPUT
    
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ steps.prepareArtifact.outputs.artifactName }}
        path: ${{ steps.prepareArtifact.outputs.artifactUpload }}

    - name: Commit and push
      run: |
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull
        git add android-app/bin/*
        git commit -m "Add compiled APK from latest commit" -a
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload to releases
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.prepareArtifact.outputs.artifactUpload }}
        asset_name: ${{ steps.prepareArtifact.outputs.artifactName }}.apk
        tag: debug-${{ github.sha }}

#################### END OF WORKFLOW ####################