##########     BASIC CALCULATOR APK BUILDER      ##########
##########          WRITTEN BY NGDPLNK           ##########

#################### START OF WORKFLOW ####################
name: Build APK

## TRIGGERS ##
on:
  push:
    branches:
      - main
    paths:
      - 'android-app/*.py'
      - 'android-app/*.kv'
      - 'android-app/*.spec'
      - 'android-app/assets/*.png'
      - '.github/workflows/build-android.yml'

## ENVIRONMENT ##
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
    - name: Checkout code
      uses: actions/checkout@master

      # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@main
      with:
        java-version: '17'
        distribution: 'adopt'

      # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential
        pip install Cython virtualenv setuptools wheel
        pip install kivy[full]
        pip install https://github.com/kivymd/KivyMD/archive/master.zip
        pip install buildozer
      
      # Build APK
    - name: Build APK
      run: |
        cd android-app/
        buildozer android debug

      # Prepare artifacts
    - name: Prepare artifact
      id: prepareArtifact
      run: |
        artifactUpload=`ls -t android-app/bin/*.apk | head -n1`
        artifactName="basiccalc-build-dev-${{ github.sha }}-arm64-v8a_armeabi-v7a-debug"
        mv $artifactUpload android-app/bin/$artifactName.apk
        artifactUpload="android-app/bin/$artifactName.apk"
        echo "artifactUpload=$artifactUpload" >> $GITHUB_OUTPUT
        echo "artifactName=$artifactName" >> $GITHUB_OUTPUT
    
      # Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ steps.prepareArtifact.outputs.artifactName }}
        path: ${{ steps.prepareArtifact.outputs.artifactUpload }}

      # Commit compiled APK
    - name: Commit compiled APK
      uses: swinton/commit@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          ${{ steps.prepareArtifact.outputs.artifactUpload }}
        commit-message: Add compiled APK from build
        ref: refs/heads/main
    
      # Upload to releases
    - name: Upload to releases
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.prepareArtifact.outputs.artifactUpload }}
        asset_name: ${{ steps.prepareArtifact.outputs.artifactName }}.apk
        tag: dev-${{ github.sha }}

#################### END OF WORKFLOW ####################